// <auto-generated />
using DicomWebApplicatioj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DicomWebApplicatioj.Migrations
{
    [DbContext(typeof(AnnotationsDBContext))]
    partial class AnnotationsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DicomWebApplicatioj.Models.Annotation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnotationNum");

                    b.Property<string>("Comment");

                    b.Property<int>("LastX");

                    b.Property<int>("LastY");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.Property<string>("colour");

                    b.Property<string>("filename");

                    b.Property<string>("labelFormat");

                    b.Property<int>("pensize");

                    b.Property<string>("shape");

                    b.HasKey("ID");

                    b.ToTable("Annotation");
                });
#pragma warning restore 612, 618
        }
    }
}
